apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  namespace: fc-pfa-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deploy
  template:
    metadata:
      labels:
        app: api-deploy
    spec:
      containers:
      - name: api-deploy
        image: giov3nn10/fc-pfa-go:api
        resources:  
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
          - containerPort: 8181
        env:
          - name: MONGO_CONNECTION_STRING
            value: mongodb://root:root@mongo-service.fc-pfa-go.svc.cluster.local:27017
          - name: SERVER_PORT
            value: '8181'
