apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: fc-pfa-go
spec:
  type: NodePort
  selector:
    app: api-deploy
  ports:
  - port: 8181
    targetPort: 8181
    nodePort: 32001
