apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  namespace: pfa-go
spec:
  replicas: 11
  selector:
    matchLabels:
      app: api-deploy
  template:
    metadata:
      labels:
        app: api-deploy
    spec:
      containers:
      - name: api-deploy
        image: giov3nn10/pfa-go:api
        env:
          - name: MONGO_CONNECTION_STRING
            value: mongodb://root:root@mongo-service.pfa-go.svc:27017
          - name: SERVER_PORT
            value: 8181
        ports:
        - containerPort: 8181
