apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  namespace: pfa-go
spec:
  replicas: 11
  selector:
    matchLabels:
      app: api-deploy
  template:
    metadata:
      labels:
        app: api-deploy
    spec:
      containers:
      - name: api-deploy
        image: giov3nn10/pfa-go:api
        ports:
        - containerPort: 8080
