apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deploy
  namespace: pfa-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-deploy
  template:
    metadata:
      labels:
        app: producer-deploy
    spec:
      containers:
      - name: goserver
        image: giov3nn10/pfa-go:producer
        env:
          - name: RABBITMQ_CONNECTION_STRING
            value: amqp://guest:guest@rabbitmq-service.pfa-go.svc.cluster.local:5672
