apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  namespace: pfa-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-deploy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo-deploy
    spec:
      containers:
      - image: mongo
        resources:  
          limits:
            memory: 512Mi
            cpu: "1"
        name: mysql
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 27017
