apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: pfa-go
spec:
  replicas: 10
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: goserver
        image: wesleywillians/pfa-go:latest
        ports:
        - containerPort: 8080
