apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deploy
  namespace: pfa-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-deploy
  template:
    metadata:
      labels:
        app: consumer-deploy
    spec:
      containers:
      - name: conumser
        image: giov3nn10/pfa-go:consumer
        resources:  
          limits:
            memory: 512Mi
            cpu: "1"
        env:
          - name: MONGO_CONNECTION_STRING
            value: mongodb://root:root@mongo-service.pfa-go.svc.cluster.local:27017
          - name: RABBITMQ_CONNECTION_STRING
            value: amqp://guest:guest@rabbitmq-service.pfa-go.svc.cluster.local:5672
          - name: MAX_CONSUMER_WORKERS
            value: '5'
