apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deploy
  namespace: pfa-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-deploy
  template:
    metadata:
      labels:
        app: consumer-deploy
    spec:
      containers:
      - name: conumser
        image: giov3nn10/pfa-go:consumer
        env:
          - name: ENVIRONMENT
            value: Production
