version: '3.7'
services:
  goapp:
    build: ../src/.
    volumes:
      - ../../src:/app
    ports:
      - "8181:8181"

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orders
      - MYSQL_PASSWORD=root
    # volumes:
    #   - ./.docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
