version: '3.7'
name: pfa-go
services:
  goapp:
    build: ../../src/.
    environment:
      - MONGO_CONNECTION_STRING=mongodb://root:root@mongo:27017
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ../../src:/app
    ports:
      - "8181:8181"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672" # service port
      - "15672:15672" # ui port
      - "15692:15692" # metrics port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ../configs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ../configs/definitions.json:/etc/rabbitmq/definitions.json:ro
