version: '3.7'
name: pfa-go
services:
  goapp:
    build: ../../src/.
    volumes:
      - ../../src:/app
    ports:
      - "8181:8181"

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - "3306:3306"
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orders
      - MYSQL_PASSWORD=root
    volumes:
      - "../scripts/schema.sql:/scripts/schema.sql"

  rabbitmq:
    image: giov3nn10/rabbitmq-monitoring
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ../configs/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ../configs/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
