apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: pfa-go
spec:
  selector:
    matchLabels:
      app: mysql-deploy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-deploy
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: orders
        ports:
        - containerPort: 3306
          name: mysql
