FROM rabbitmq:3.8.16-management

RUN rabbitmq-plugins enable --offline rabbitmq_prometheus rabbitmq_tracing

ADD rabbitmq.config /etc/rabbitmq
ADD definitions.json /etc/rabbitmq

RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.config
RUN chown rabbitmq:rabbitmq /etc/rabbitmq/definitions.json

CMD ["rabbitmq-server"]
