apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deploy
  namespace: pfa-go
  labels:
    app: prometheus-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-deploy
  template:
    metadata:
      labels:
        app: prometheus-deploy
    spec:
      containers:
        - name: prometheus
          image: prometheus
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
      volumes:
        - name: prometheus
          configMap:
            defaultMode: 420
            name: prometheus-configmap

