apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deploy
  namespace: pfa-go
  labels:
    app: prometheus-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-deploy
  template:
    metadata:
      labels:
        app: prometheus-deploy
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-volume
          configMap:
            defaultMode: 420
            name: prometheus-configmap

