
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-configmap
  namespace: pfa-go
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.pfa-go.svc.cluster.local:8080",
                "version": 1
            }
        ]
    }
