apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  namespace: pfa-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-deploy
  template:
    metadata:
      name: grafana-deploy
      labels:
        app: grafana-deploy
    spec:
      containers:
      - name: grafana-deploy
        image: grafana/grafana
        resources:  
          limits:
            memory: 512Mi
            cpu: "1"
        env:
          - name: GF_INSTALL_PLUGINS
            value: 'grafana-clock-panel,grafana-simple-json-datasource'
          - name: GF_SECURITY_ADMIN_USER
            value: admin
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: admin
          - name: GF_USERS_ALLOW_SIGN_UP
            value: 'false'
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
          - name: grafana-datasource-configmap
            mountPath: /etc/grafana/provisioning/datasources
            readOnly: false
          - name: grafana-dashboard-configmap
            mountPath: /etc/grafana/provisioning/dashboards
            readOnly: false
      volumes:
        - name: grafana-datasource-configmap
          configMap:
            defaultMode: 420
            name: grafana-datasource-configmap
        - name: grafana-dashboard-configmap
          configMap:
            defaultMode: 420
            name: grafana-dashboard-configmap
    
