apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  namespace: pfa-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-deploy
  template:
    metadata:
      name: grafana-deploy
      labels:
        app: grafana-deploy
    spec:
      containers:
      - name: grafana-deploy
        image: grafana/grafana
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
          - name: grafana-volume
            mountPath: /etc/grafana/provisioning/datasources
            readOnly: false
      volumes:
        - name: grafana-volume
          configMap:
            defaultMode: 420
            name: grafana-configmap
    
