apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: pfa-go
spec:
  replicas: 10
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: goserver
        image: wesleywillians/pfa-go:latest
        ports:
        - containerPort: 8080
