apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
  labels:
    name: rabbitmq-configmap
  namespace: fc-pfa-go
data:
  enabled_plugins: |-
    [rabbitmq_management,rabbitmq_management_visualiser, rabbitmq_prometheus].
  
  rabbitmq.conf: |-
    management.load_definitions = /etc/rabbitmq/definitions.json
    loopback_users.guest = false
    listeners.tcp.default = 5672
    default_pass = guest
    default_user = guest
    default_vhost = /

  definitions.json: |-
    {
      "users": [
          {
              "name": "guest",
              "password_hash": "BMfxN8drrYcIqXZMr+pWTpDT0nMcOagMduLX0bjr4jwud/pN",
              "hashing_algorithm": "rabbit_password_hashing_sha256",
              "tags": [
                  "administrator"
              ],
              "limits": {}
          }
      ],
      "vhosts": [
          {
              "name": "/"
          }
      ],
      "permissions": [
          {
              "user": "guest",
              "vhost": "/",
              "configure": ".*",
              "write": ".*",
              "read": ".*"
          }
      ],
      "queues": [
          {
              "name": "orders",
              "vhost": "/",
              "durable": true,
              "auto_delete": false,
              "arguments": {
                  "x-queue-type": "classic"
              }
          }
      ],
      "bindings": [
          {
              "source": "amq.direct",
              "vhost": "/",
              "destination": "orders",
              "destination_type": "queue",
              "routing_key": "orders",
              "arguments": {}
          }
      ]
    }
