apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  labels:
    app: rabbitmq-deploy
  namespace: pfa-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-deploy
  template:
    metadata:
      labels:
        app: rabbitmq-deploy
    spec:
      containers:
        - name: rabbitmq-deploy
          image: giov3nn10/rabbitmq-monitoring:latest
          ports:
            - containerPort: 15672
              name: http
            - containerPort: 5672
              name: amqp
            - containerPort: 15692
              name: prometheus
          volumeMounts:
            - name: rabbitmq-volume
              mountPath: /etc/rabbitmq/
      volumes:
        - name: rabbitmq-volume
          configMap:
            name: rabbitmq-configmap
