apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-deploy
  namespace: pfa-go
spec:
  type: NodePort
  selector:
    app: rabbitmq-deploy
  ports:
  - port: 15672
    nodePort: 31672
    name: http
  - port: 5672
    name: amqp
  - port: 15692
    nodePort: 30672
    name: prometheus
