apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
  namespace: pfa-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-deploy
  template:
    metadata:
      labels:
        app: rabbitmq-deploy
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8.16-management
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: guest
          - name: RABBITMQ_DEFAULT_PASS
            value: guest
          - name: RABBITMQ_DEFAULT_VHOST
            value: /
        ports:
          - name: http
            containerPort: 15672
          - name: amqp
            containerPort: 5672
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 1
            memory: 1Gi
